name: build docker container
run-name: ${{ github.actor }} is creating the new docker release of the container
on:
  push:
    branches:
      - 'main'

jobs:
  build_and_push_container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: carnivuth/curiel_bot:latest
      - 
        name: Delete logs
        shell: bash
        run: Delete_logs.sh curiel_bot 'build docker container'
